#!/bin/bash

EXEC_FILE="./hello_human"

function echo_green {
	printf "\e[32m${@}\e[0m\n"
}

echo_green "Making..."
make re
echo_green "Running in background..."
$EXEC_FILE &
sleep 2
PID=`ps | grep "$EXEC_FILE" | head -n 1 | sed -e 's/^[[:space:]]*//' | cut -d" " -f1`
echo_green "Found PID: $PID"
echo_green "Running leaks..."
leaks "$PID"
echo_green "Stopping..."
kill "$PID"
echo_green "Done."
